pipeline {
    agent any
    
    environment {
        STACK_NAME = "todo-list-production"
        REGION = "us-east-1"
        PY_HOME = "C:\\Users\\Ghost\\AppData\\Local\\Programs\\Python\\Python311"
        PY_SCRIPTS = "C:\\Users\\Ghost\\AppData\\Local\\Programs\\Python\\Python311\\Scripts"
    }

    stages {
        stage('Get Code') {
            steps {
                git branch: 'master', url: 'https://github.com/santvaz/todo-list-aws.git'
            }
        }

        stage('Build') {
            steps {
                echo 'Iniciando SAM Build...'
                withEnv(["PATH+EXTRA=${env.PY_HOME};${env.PY_SCRIPTS}"]) {
                    bat "sam build"
                }
            }
        }

        stage('Deploy') {
            steps {
                echo 'Desplegando en entorno PRODUCTION...'
                withEnv(["PATH+EXTRA=${env.PY_HOME};${env.PY_SCRIPTS}"]) {
                    withCredentials([
                        string(credentialsId: 'AWS_ACCESS_KEY_ID', variable: 'AWS_ACCESS_KEY_ID'),
                        string(credentialsId: 'AWS_SECRET_ACCESS_KEY', variable: 'AWS_SECRET_ACCESS_KEY')
                    ]) {
                        bat """
                        sam deploy ^
                            --config-env production ^
                            --stack-name ${env.STACK_NAME} ^
                            --region ${env.REGION} ^
                            --capabilities CAPABILITY_IAM ^
                            --no-confirm-changeset ^
                            --no-fail-on-empty-changeset ^
                            --resolve-s3 ^
                            --parameter-overrides Stage=production
                        """
                    }
                }
            }
        }

        stage('Rest Test (Read Only)') {
            steps {
                script {
                    withCredentials([
                        string(credentialsId: 'AWS_ACCESS_KEY_ID', variable: 'AWS_ACCESS_KEY_ID'),
                        string(credentialsId: 'AWS_SECRET_ACCESS_KEY', variable: 'AWS_SECRET_ACCESS_KEY')
                    ]) {
                        def BASE_URL = bat(
                            script: "aws cloudformation describe-stacks --stack-name ${env.STACK_NAME} --query \"Stacks[0].Outputs[?OutputKey=='BaseUrlApi'].OutputValue\" --region ${env.REGION} --output text",
                            returnStdout: true
                        ).trim()
                        
                        echo "URL de Producción detectada: ${BASE_URL}"
                        
                        echo 'Iniciando Pruebas de lectura con Curl...'
                        bat "curl -I -X GET ${BASE_URL}/todos"
                    }
                }
            }
        }
    }

    post { 
        always { 
            echo 'Limpiando espacio de trabajo...'
            cleanWs()
        }
        success {
            echo '¡RETOCADO! Despliegue en Producción finalizado correctamente.'
        }
    }
}